package cloud.iot.ai.analytics.element;

import java.util.Arrays;
import java.util.List;

public class SchematronConstants {
	public static final String ISO_SCHEMATRON_NAMESPACE_URI = "http://purl.oclc.org/dsdl/schematron";
	public static final String ASCC_SCHEMATRON_NAMESPACE_URI = "http://www.ascc.net/xml/schematron";
	public static final List<String> SCHEMATRON_NAMESPACE_URI = Arrays
			.asList(new String[] { ISO_SCHEMATRON_NAMESPACE_URI, ASCC_SCHEMATRON_NAMESPACE_URI });
	public static final String SCHEMATRON_DEFAULT_PREFIX = "sch";
	public static final String SCHEMATRON_ELEMENT_SCHEMA = "schema";
	public static final String SCHEMATRON_ELEMENT_TITLE = "title";
	public static final String SCHEMATRON_ELEMENT_NS = "ns";
	public static final String SCHEMATRON_ELEMENT_LET = "let";
	public static final String SCHEMATRON_ELEMENT_PARAM = "param";
	public static final String SCHEMATRON_ELEMENT_INCLUDE = "include";
	public static final String SCHEMATRON_ELEMENT_PHASE = "phase";
	public static final String SCHEMATRON_ELEMENT_P = "p";
	public static final String SCHEMATRON_ELEMENT_DIAGNOSTICS = "diagnostics";
	public static final String SCHEMATRON_ELEMENT_DIAGNOSTIC = "diagnostic";
	public static final String SCHEMATRON_ELEMENT_ACTIVE = "active";
	public static final String SCHEMATRON_ELEMENT_PATTERN = "pattern";
	public static final String SCHEMATRON_ELEMENT_RULE = "rule";
	public static final String SCHEMATRON_ELEMENT_EXTENDS = "extends";
	public static final String SCHEMATRON_ELEMENT_ASSERT = "assert";
	public static final String SCHEMATRON_ELEMENT_REPORT = "report";
	public static final String SCHEMATRON_ELEMENT_VALUEOF = "value-of";
	public static final String SCHEMATRON_ELEMENT_NAME = "name";
	public static final String SCHEMATRON_ELEMENT_DIR = "dir";
	public static final String SCHEMATRON_ELEMENT_EMPH = "emph";
	public static final String SCHEMATRON_ELEMENT_SPAN = "span";
	public static final String SCHEMATRON_ATTRIBUTE_URI = "uri";
	public static final String SCHEMATRON_ATTRIBUTE_PREFIX = "prefix";
	public static final String SCHEMATRON_ATTRIBUTE_ID = "id";
	public static final String SCHEMATRON_ATTRIBUTE_CLASS_VALUE = "class";
	public static final String SCHEMATRON_ATTRIBUTE_ICON = "icon";
	public static final String SCHEMATRON_ATTRIBUTE_SEE = "see";
	public static final String SCHEMATRON_ATTRIBUTE_FPI = "fpi";
	public static final String SCHEMATRON_ATTRIBUTE_LANG = "xml:lang";
	public static final String SCHEMATRON_ATTRIBUTE_SPACE = "xml:space";
	public static final String SCHEMATRON_ATTRIBUTE_ROLE = "role";
	public static final String SCHEMATRON_ATTRIBUTE_SUBJECT = "subject";
	public static final String SCHEMATRON_ATTRIBUTE_DIAGNOSTICS = "diagnostics";
	public static final String SCHEMATRON_ATTRIBUTE_ABSTRACT = "abstract";
	public static final String SCHEMATRON_ATTRIBUTE_TITLE = "title";
	public static final String SCHEMATRON_ATTRIBUTE_CONTEXT = "context";
	public static final String SCHEMATRON_ATTRIBUTE_ENABLEALL = "enableAll";
	public static final String SCHEMATRON_ATTRIBUTE_FLAG = "flag";
	public static final String SCHEMATRON_ATTRIBUTE_LOCATION = "location";
	public static final String SCHEMATRON_ATTRIBUTE_TEST = "test";
	public static final String SCHEMATRON_ATTRIBUTE_SELECT = "select";
	public static final String SCHEMATRON_ATTRIBUTE_PATH = "path";
	public static final String SCHEMATRON_ATTRIBUTE_NAME = "name";
	public static final String SCHEMATRON_ATTRIBUTE_VALUE = "value";
	public static final String SCHEMATRON_ATTRIBUTE_HREF = "href";
	public static final String SCHEMATRON_ATTRIBUTE_RULE = "rule";
	public static final String SCHEMATRON_ATTRIBUTE_IS_A = "is-a";
	public static final String SCHEMATRON_ATTRIBUTE_FORMAL = "formal";
	public static final String SCHEMATRON_ATTRIBUTE_ACTUAL = "actual";
	public static final String SCHEMATRON_ATTRIBUTE_PATTERN = "pattern";
	public static final String SCHEMATRON_ATTRIBUTE_DEFAULT_PHASE = "defaultPhase";
	public static final String SCHEMATRON_PHASE_VALUE_ALL = "#ALL";
	public static final String SCHEMATRON_PHASE_VALUE_DEFAULT = "#DEFAULT";
	public static final String SCHEMATRON_NAME_VALUE = "name";
	public static final String SCHEMATRON_NAME_ELEMENT_VALUE = "name(.)";
	public static final String SCHEMATRON_XML_SPACE_VALUE_DEFAULT = "default";
	public static final String SCHEMATRON_XML_SPACE_VALUE_PRESERVE = "preserve";
}
